apiVersion: v1
kind: Service
metadata:
  name: postgres-pingpong-app-svc
spec:
  type: LoadBalancer # This should be the only unfamiliar part
  selector:
    app: postgres-pingpong-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000