apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: to-do-front-ingress
  namespace: project
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: to-do-front-svc
            port:
              number: 2346
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: to-do-back-svc
            port:
              number: 2347