apiVersion: v1
kind: Service
metadata:
  name: to-do-svc
spec:
  type: ClusterIP
  selector:
    app: to-do
  ports:
    - port: 2345
      name: to-do-back-svc
      protocol: TCP
      targetPort: 3001
    - port: 2346
      name: to-do-front-svc
      protocol: TCP
      targetPort: 3004