apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: shared-logs-claim
        - name:  postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-claim3
      containers:
        - name: db
          image: postgres
          volumeMounts: 
          - name: postgres-data
            mountPath: /var/lib/postgresql
          env:
          - name: POSTGRES_PASSWORD
            value: "example"
        - name: ping-pong
          image: titunidoc/devops_pingpong:2.714
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/src/app/files
          env:
          - name: PORT
            value: "3001"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASS
            value: "example"
          - name: DB_HOST
            value: "db"
          - name: DB_PORT
            value: "5432"
          - name: DB_TYPE
            value: "pg"
          - name: DB_DATABASE
            value: "postgres"
       