apiVersion: v1
kind: Service
metadata:
  name: ping-pong-lb-svc
  namespace: exercises
spec:
  type: NodePort #LoadBalancer 
  selector:
    app: postgres-pingpong-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001