apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-file-ingress
spec:
  rules:
  - http:
      paths:
      - path: /logs
        pathType: Prefix
        backend:
          service:
            name: log-file-svc
            port:
              number: 2346