apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do
spec:
  replicas: 1
  selector:
    matchLabels:
      app: to-do
  template:
    metadata:
      labels:
        app: to-do
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: shared-logs-claim
      containers:
        - name: to-do
          image: titunidoc/devops_kubernetes:1.52
          mountPath: /usr/src/app/files
          env:
          - name: PORT
            value: "3001"
          - name: DB_USER
            value: "root"
          - name: DB_PASS
            value: "mypass123"
          - name: DB_HOST
            value: "localhost"
          - name: DB_PORT
            value: "3306"
          - name: DB_TYPE
            value: "mysql2"  
          - name: DB_DATABASE
            value: "notes_db"
          - name: SECRET
            value: "tosisalainensalasanainen"
            volumeMounts:
          - name: shared-logs
          