apiVersion: v1
kind: Service
metadata:
  name: to-do-svc
spec:
  type: NodePort
  selector:
    app: to-do
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 3000