apiVersion: v1
data:
  DB_DATABASE: postgres
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-29T11:25:10Z"
  name: project.database
  namespace: project
---
apiVersion: v1
data:
  DB_PASS: example
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-29T11:25:32Z"
  name: project.dbpass
  namespace: project
---
apiVersion: v1
data:
  DB_USER: postgres
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-29T11:25:51Z"
  name: project.dbuser
  namespace: project
---
apiVersion: v1
data:
  DB_HOST: localhost
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-29T11:26:22Z"
  name: project.dbhost
  namespace: project
---
apiVersion: v1
data:
  POSTGRES_PASSWORD: example
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-29T18:11:10Z"
  name: project.pgpass
  namespace: project