apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-claim3 # name of the volume claim, this will be used in the deployment
  namespace: exercises
spec:
  storageClassName: postgres-data2-pv # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi