apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-front
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: to-do-front
  template:
    metadata:
      labels:
        app: to-do-front
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: project-cache-claim
      containers:
        - name: to-do-front
          image: titunidoc/devops_kubernetes:front_2.26 
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/src/app/files
          env:
          - name: PORT
            value: "3005"     
          