apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: to-do-back
  template:
    metadata:
      labels:
        app: to-do-back
    spec:
      containers:
        - name: to-do-back
          image: titunidoc/devops_kubernetes:back_2.26
          env:
          - name: PORT
            value: "3004"
          - name: DB_USER
            value: "root"
          - name: DB_PASS
            value: "mypass123"
          - name: DB_HOST
            value: "localhost"
          - name: DB_PORT
            value: "3306"
          - name: DB_TYPE
            value: "mysql2"  
          - name: DB_DATABASE
            value: "notes_db"
          - name: SECRET
            value: "tosisalainensalasanainen"
     
          