apiVersion: v1
kind: Service
metadata:
  name: log-file-lb-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: log-file
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
