name: Cleanup feature deployment

on:
  delete:
    branches:
      - feature-*

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north2-b
  REGISTRY: europe-north2-docker.pkg.dev
  REPOSITORY: my-repository
  IMAGE_BACK: todo-back
  IMAGE_FRONT: todo-front
  IMAGE_CRON: todo-cron
  SERVICE: todo-service
  BRANCH: ${{ github.ref_name }}
  NS_NAME: ${{ github.ref_name }} 

jobs:
  build-publish-deploy:
    name: Cleanup deployment for feature branch
    runs-on: ubuntu-latest
    environment: sirit

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker europe-north2-docker.pkg.dev

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'
      
      - name: Cleanup
        run: |-
          # --ignore-not-found estää putkea kaatumasta, jos se on jo poistettu
          kubectl delete namespace $NS_NAME --ignore-not-found

  