name: Release application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north2-b
  REGISTRY: europe-north2-docker.pkg.dev
  REPOSITORY: my-repository
  IMAGE_BACK: todo-back
  IMAGE_FRONT: todo-front
  IMAGE_CRON: todo-cron
  SERVICE: todo-service
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    environment: sirit

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker europe-north2-docker.pkg.dev

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name : 'Form the image name for back'
        run: echo "IMAGE_TAG_BACK=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_BACK:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build
        run: docker build --tag $IMAGE_TAG_BACK ./the_project/backend

      - name: Publish
        run: docker push $IMAGE_TAG_BACK

      - name : 'Form the image name for front'
        run: echo "IMAGE_TAG_FRONT=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_FRONT:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build
        run: docker build --tag $IMAGE_TAG_FRONT ./the_project/front

      - name: Publish
        run: docker push $IMAGE_TAG_FRONT

      - name : 'Form the image name for cron'
        run: echo "IMAGE_TAG_CRON=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_CRON:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build
        run: docker build --tag $IMAGE_TAG_CRON ./the_project

      - name: Publish
        run: docker push $IMAGE_TAG_CRON  

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0
      
      - name: Deploy
        run: |-
          kustomize edit set image PROJECT/IMAGE_BACK=$IMAGE_TAG_BACK
          kustomize edit set image PROJECT/IMAGE_FRONT=$IMAGE_TAG_FRONT
          kustomize edit set image PROJECT/IMAGE_CRON=$IMAGE_TAG_CRON
          kustomize build . | kubectl apply -k --server-side 
          if ! kubectl rollout status deployment/$SERVICE --namespace project --timeout=10m; then
            echo "Rollout ep√§onnistui, perutaan muutokset..."
            kubectl rollout undo deployment/$SERVICE --namespace project
            exit 1
          fi
          kubectl get services -o wide --namespace project